### ISSUE TITLE
rustfmt-nightly-aarch64-apple-darwin.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found

### ISSUE THREAD

**Issue by pablo-guardiola** [bitdriftlabs/capture-sdk#14]
As I continue my journey exploring `capture-sdk`'s repo / learning how bitdrift's Capture SDK works (refs. https://github.com/bitdriftlabs/capture-sdk/issues/13) noticed the following warning when running `$> ./bazelw test //platform/jvm/...` ⚠️ 

```
➜  capture-sdk git:(main) ✗ ./bazelw test //platform/jvm/...
Starting local Bazel server and connecting to it...
WARNING: Download from https://github.com/bitdriftlabs/rust-std-mobile/releases/download/1.80.1/2024-07-24/rustfmt-nightly-aarch64-apple-darwin.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

cc @murki

**Comment by Reflejo** [comment]
Those 404s are expected and not a real problem. The way rust resources pulling work is, we have two mirrors: 

1. One we control (rust-std-mobile)
2. The official rust channel

We only serve a subset of libraries on 1 (namely, the rust std for all archs); the ones we don't serve will 404 on (1) but work on (2).

**Comment by pablo-guardiola** [comment]
Thanks a lot for the detailed answer @Reflejo  It makes total sense. I was only flagging just in case may be an issue 👍 

Closing as answered.
